// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 8.3.11
// Project name: UdemyProductivityTimer

#include "ui.h"

void ui_event_comp_Button_Start_Stop_Button_Start_Stop(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t ** comp_Button_Start_Stop = lv_event_get_user_data(e);

    if(event_code == LV_EVENT_CLICKED) {
        button_start_stop_clicked(e);
    }
}

// COMPONENT Button_Start_Stop

lv_obj_t * ui_Button_Start_Stop_create(lv_obj_t * comp_parent)
{

    lv_obj_t * cui_Button_Start_Stop;
    cui_Button_Start_Stop = lv_btn_create(comp_parent);
    lv_obj_set_width(cui_Button_Start_Stop, 100);
    lv_obj_set_height(cui_Button_Start_Stop, 50);
    lv_obj_set_x(cui_Button_Start_Stop, 20);
    lv_obj_set_y(cui_Button_Start_Stop, 135);
    lv_obj_set_align(cui_Button_Start_Stop, LV_ALIGN_CENTER);
    lv_obj_add_flag(cui_Button_Start_Stop, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(cui_Button_Start_Stop, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_t * cui_Label3;
    cui_Label3 = lv_label_create(cui_Button_Start_Stop);
    lv_obj_set_width(cui_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(cui_Label3, LV_ALIGN_CENTER);
    lv_label_set_text(cui_Label3, "START/STOP");

    lv_obj_t ** children = lv_mem_alloc(sizeof(lv_obj_t *) * _UI_COMP_BUTTON_START_STOP_NUM);
    children[UI_COMP_BUTTON_START_STOP_BUTTON_START_STOP] = cui_Button_Start_Stop;
    children[UI_COMP_BUTTON_START_STOP_LABEL3] = cui_Label3;
    lv_obj_add_event_cb(cui_Button_Start_Stop, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
    lv_obj_add_event_cb(cui_Button_Start_Stop, del_component_child_event_cb, LV_EVENT_DELETE, children);
    lv_obj_add_event_cb(cui_Button_Start_Stop, ui_event_comp_Button_Start_Stop_Button_Start_Stop, LV_EVENT_ALL, children);
    ui_comp_Button_Start_Stop_create_hook(cui_Button_Start_Stop);
    return cui_Button_Start_Stop;
}

