// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 8.3.11
// Project name: UdemyProductivityTimer

#ifndef _UI_COMP_BUTTON_START_STOP_H
#define _UI_COMP_BUTTON_START_STOP_H

#include "ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT Button_Start_Stop
#define UI_COMP_BUTTON_START_STOP_BUTTON_START_STOP 0
#define UI_COMP_BUTTON_START_STOP_LABEL3 1
#define _UI_COMP_BUTTON_START_STOP_NUM 2
lv_obj_t * ui_Button_Start_Stop_create(lv_obj_t * comp_parent);
void ui_event_comp_Button_Start_Stop_Button_Start_Stop(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
