// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 8.3.11
// Project name: UdemyProductivityTimer

#include "ui.h"

void button_up_clicked_cb(lv_event_t * e)
{
	// Your code here
}

void button_down_clicked_cb(lv_event_t * e)
{
	// Your code here
}

void button_start_stop_clicked(lv_event_t * e)
{
	// Your code here
}
