// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 8.3.11
// Project name: UdemyProductivityTimer

#ifndef UI_SCREEN1_H
#define UI_SCREEN1_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen1
extern void ui_Screen1_screen_init(void);
extern void ui_Screen1_screen_destroy(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_Container2;
extern void ui_event_ButtonUP(lv_event_t * e);
extern lv_obj_t * ui_ButtonUP;
extern lv_obj_t * ui_Label1;
extern void ui_event_ButtonDown(lv_event_t * e);
extern lv_obj_t * ui_ButtonDown;
extern lv_obj_t * ui_Label2;
extern void ui_event_ButtonStartStop(lv_event_t * e);
extern lv_obj_t * ui_ButtonStartStop;
extern lv_obj_t * ui_Label4;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

