// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 8.3.11
// Project name: UdemyProductivityTimer

#include "ui.h"

lv_obj_t * ui_Screen1;
lv_obj_t * ui_Container2;
lv_obj_t * ui_ButtonUP;
lv_obj_t * ui_Label1;
lv_obj_t * ui_ButtonDown;
lv_obj_t * ui_Label2;
lv_obj_t * ui_ButtonStartStop;
lv_obj_t * ui_Label4;

// event funtions
void ui_event_ButtonUP(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        button_up_clicked_cb(e);
    }
}

void ui_event_ButtonDown(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        button_down_clicked_cb(e);
    }
}

void ui_event_ButtonStartStop(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        button_start_stop_clicked(e);
    }
}

// build funtions

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Container2 = lv_obj_create(ui_Screen1);
    lv_obj_remove_style_all(ui_Container2);
    lv_obj_set_width(ui_Container2, 528);
    lv_obj_set_height(ui_Container2, 112);
    lv_obj_set_x(ui_Container2, 19);
    lv_obj_set_y(ui_Container2, -20);
    lv_obj_set_align(ui_Container2, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container2, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container2, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_Container2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ButtonUP = lv_btn_create(ui_Container2);
    lv_obj_set_width(ui_ButtonUP, 100);
    lv_obj_set_height(ui_ButtonUP, 50);
    lv_obj_set_x(ui_ButtonUP, -240);
    lv_obj_set_y(ui_ButtonUP, 124);
    lv_obj_set_align(ui_ButtonUP, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonUP, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ButtonUP, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label1 = lv_label_create(ui_ButtonUP);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label1, "UP");

    ui_ButtonDown = lv_btn_create(ui_Container2);
    lv_obj_set_width(ui_ButtonDown, 100);
    lv_obj_set_height(ui_ButtonDown, 50);
    lv_obj_set_x(ui_ButtonDown, -119);
    lv_obj_set_y(ui_ButtonDown, 126);
    lv_obj_set_align(ui_ButtonDown, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonDown, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ButtonDown, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label2 = lv_label_create(ui_ButtonDown);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label2, "DOWN");

    ui_ButtonStartStop = lv_btn_create(ui_Container2);
    lv_obj_set_width(ui_ButtonStartStop, 100);
    lv_obj_set_height(ui_ButtonStartStop, 50);
    lv_obj_set_x(ui_ButtonStartStop, 20);
    lv_obj_set_y(ui_ButtonStartStop, 135);
    lv_obj_set_align(ui_ButtonStartStop, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonStartStop, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ButtonStartStop, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label4 = lv_label_create(ui_ButtonStartStop);
    lv_obj_set_width(ui_Label4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label4, "START/STOP");

    lv_obj_add_event_cb(ui_ButtonUP, ui_event_ButtonUP, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ButtonDown, ui_event_ButtonDown, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ButtonStartStop, ui_event_ButtonStartStop, LV_EVENT_ALL, NULL);

}

void ui_Screen1_screen_destroy(void)
{
    if(ui_Screen1) lv_obj_del(ui_Screen1);

    // NULL screen variables
    ui_Screen1 = NULL;
    ui_Container2 = NULL;
    ui_ButtonUP = NULL;
    ui_Label1 = NULL;
    ui_ButtonDown = NULL;
    ui_Label2 = NULL;
    ui_ButtonStartStop = NULL;
    ui_Label4 = NULL;

}
